# Site settings

title: 968
url: "https://trolit.github.io/jekyll-portfolio"
baseurl: ""

# OPTIONAL CHANGES
theme-home: theme-home.html
theme-projects: theme-projects.html
theme-posts: theme-posts.html
theme-music: theme-music.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: gruvbox

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]
