# Site settings

title: 968
url: "https://trolit.github.io"
baseurl: ""

# OPTIONAL CHANGES
theme-home: theme-home-builtin-2.html
theme-projects: theme-projects-builtin-1a.html
theme-essays: theme-essays-builtin-1a.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: gruvbox

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

